/*
Tarea #1 Triggers
*/
CREATE TRIGGER `BEFORE_INSERT` BEFORE INSERT ON `contxi_peticiones`

BEGIN
IF NEW.ID_ESTADO = 2 THEN
	IF NEW.ID_TECNICOS IS NULL THEN
		Set NEW.ID_TECNICOS=1;
	ELSE
		Set NEW.ID_ESTADO=1;
	end if;
END IF;
IF NEW.ID_TECNICOS IS NOT NULL THEN
    set NEW.ID_ESTADO=2;
END IF;
END


CREATE TRIGGER `BEFORE_UPDATE` BEFORE UPDATE ON `contxi_peticiones` 
BEGIN

IF (OLD.ID_ESTADO =2 and NEW.ID_ESTADO IS NULL) or
 NEW.ID_ESTADO=2 THEN
	
	IF OLD.ID_TECNICOS IS NULL AND NEW.ID_TECNICOS IS NULL THEN
		Set NEW.ID_TECNICOS=1;
	end if;
END IF;

IF OLD.ID_TECNICOS IS NOT NULL and NEW.ID_TECNICOS IS NULL 
or NEW.ID_TECNICOS IS NOT NULL
THEN
    set NEW.ID_ESTADO=2;
END IF;
END


CREATE TRIGGER `BEFORE_INSERT_MAYUS` BEFORE INSERT ON `contxi_peticionarios` 
BEGIN

SET NEW.NOMBRE_APELLIDOS= LOWER(CONVERT(NEW.NOMBRE_APELLIDOS USING utf8mb4));

SET NEW.NOMBRE_APELLIDOS = REPLACE(NEW.NOMBRE_APELLIDOS,'á','a');
SET NEW.NOMBRE_APELLIDOS = REPLACE(NEW.NOMBRE_APELLIDOS,'é','e');
SET NEW.NOMBRE_APELLIDOS = REPLACE(NEW.NOMBRE_APELLIDOS,'í','i');
SET NEW.NOMBRE_APELLIDOS = REPLACE(NEW.NOMBRE_APELLIDOS,'ó','o');
SET NEW.NOMBRE_APELLIDOS = REPLACE(NEW.NOMBRE_APELLIDOS,'ú','u');

SET NEW.NOMBRE_APELLIDOS= UPPER(NEW.NOMBRE_APELLIDOS);
END

CREATE TRIGGER `BEFORE_UPDATE_MAYUS` BEFORE UPDATE ON `contxi_peticionarios` 
BEGIN

IF NEW.NOMBRE_APELLIDOS IS NULL THEN

SET NEW.NOMBRE_APELLIDOS= LOWER(CONVERT(OLD.NOMBRE_APELLIDOS USING utf8));

ELSE

SET NEW.NOMBRE_APELLIDOS= LOWER(CONVERT(NEW.NOMBRE_APELLIDOS USING utf8));
END IF;

SET NEW.NOMBRE_APELLIDOS = REPLACE(NEW.NOMBRE_APELLIDOS,'á','a');
SET NEW.NOMBRE_APELLIDOS = REPLACE(NEW.NOMBRE_APELLIDOS,'é','e');
SET NEW.NOMBRE_APELLIDOS = REPLACE(NEW.NOMBRE_APELLIDOS,'í','i');
SET NEW.NOMBRE_APELLIDOS = REPLACE(NEW.NOMBRE_APELLIDOS,'ó','o');
SET NEW.NOMBRE_APELLIDOS = REPLACE(NEW.NOMBRE_APELLIDOS,'ú','u');
SET NEW.NOMBRE_APELLIDOS = UPPER(NEW.NOMBRE_APELLIDOS);
END